FROM ubuntu:latest
FROM node:18.19.1
USER root
WORKDIR /app
RUN apt-get update 

RUN apt-get -y install curl gnupg python3 python3-pip ffmpeg

RUN curl -L -o yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
RUN chmod +x yt-dlp
RUN mv yt-dlp /usr/local/bin/yt-dlp


COPY . .

RUN npm install

EXPOSE 5002


CMD ["npm" , "start"]