FROM node:18.19.1

USER root

WORKDIR /app

RUN apt-get update && apt-get -y install curl gnupg python3 python3-pip ffmpeg cron

# Install yt-dlp
RUN curl -L -o /usr/local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
    && chmod +x /usr/local/bin/yt-dlp

# Copy application code
COPY . .

# Install Node.js dependencies
RUN npm install

# Expose the port
ENV PORT 5002
EXPOSE 5002

# Start cron and your Node.js application
CMD npm start
